CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    price numeric NOT NULL,
    stock numeric NOT NULL DEFAULT 0,
    CONSTRAINT product_pkey PRIMARY KEY (id)
)